### ISSUE TITLE
Missing attribute in Map

### ISSUE THREAD

**Issue by t-rekttt** [lakshanthad/Wio_Terminal_Classroom_Ardupy#1]
I'm trying to run [this](https://github.com/lakshanthad/Wio_Terminal_Classroom_Ardupy/blob/main/Classroom%204/Musical_Keyboard.py) example, and the error below happens and got logged inside Putty. I tried to see the attributes in Map but see some attributes are missing.
![image](https://user-images.githubusercontent.com/9071846/97608087-75b7a500-1a44-11eb-91d7-c666874e45b2.png)

**Comment by lakshanthad** [comment]
Hi,
It seems like you are missing some attributes in Map function. It is actually supposed to be like this.
![1604247483(1)](https://user-images.githubusercontent.com/20147381/97808308-37acc200-1c8c-11eb-87cb-5c5520de2148.png)
How did you flash the ArduPy firmware to Wio Terminal? Did you drag and drop the .uf2 file or did you use the AIP tool in command line?
And which operating system are you running on your PC?

**Comment by t-rekttt** [comment]
I flashed it by drag and dropping the .uf2 file downloaded from [this](https://files.seeedstudio.com/wiki/Wio-Terminal/res/ArduPy_wio_terminal_lastest.uf2) link.
My operating system is Windows 10

**Comment by lakshanthad** [comment]
Could you try to flash it again using the AIP tool on command line? It's recommended to use this method because, if there is a firmware update, it will automatically flash the latest firmware. 
You can use the AIP tool in command line to flash the firmware using the below methods:

- Follow [this ](https://wiki.seeedstudio.com/ArduPy/#install-aip-with-windows)section of the wiki page 
- Watch [this](https://youtu.be/6LN3u7zuwlQ) YouTube video and follow along

**Comment by t-rekttt** [comment]
I built the firmware and flashed it as the instruction, and I think it worked (I'll do further checks later).
Meanwhile, I think the dev team should check on the latest firmware on the website a little bit (or at least put a precaution message for it).
Thanks for helping!

Here is a comparison of the attributes of firmware flashed using aip (left) and flashed using uf2 file (right)
![image](https://user-images.githubusercontent.com/9071846/97810607-a8150c80-1ca7-11eb-8d31-708c77bd1083.png)

**Comment by lakshanthad** [comment]
great to hear that it works! Will inform about the latest firmware details issue to the dev team. thank you for your inputs!

It's my pleasure to help!
