### ISSUE TITLE
Examples for accelerometer, IR emitter, light sensor, USB OTG and microSD card slot

### ISSUE THREAD

**Issue by ruppde** [lakshanthad/Wio_Terminal_Classroom_Ardupy#3]
hello,

could you please show some examples on how to use the accelerometer, IR emitter, light sensor, USB OTG and microSD card slot?

regards
arnim

**Comment by lakshanthad** [comment]
Hi, 

Have you already followed the Wio Terminal Classroom with Arduino Video Series?
https://www.youtube.com/playlist?list=PLpH_4mf13-A0MzOdPNITVfoVBMvf7Rg9g

I have done the above-mentioned examples there. You could take the Arduino demos as a reference and transfer them to ArduPy as well.

Best Regards,
Lakshantha

**Comment by ruppde** [comment]
ok, and where would I find the proper function names and paramters? are they 100% the same?

**Comment by ruppde** [comment]
from checking ArduPy/ports/samd/boards/wio_terminal/mod_machine_map.c I would say it's not there at all?

**Comment by ruppde** [comment]
and it'll never come since the last update to ardupy was in august 2020 ...

**Comment by lakshanthad** [comment]
Hi,

You could find the function names by entering the REPL environment via serial communication.

Please watch this video from 12:02 timestamp:
https://youtu.be/9nuhsdrizps

- First, enter bootloader mode of the Wio Terminal:
https://wiki.seeedstudio.com/Wio-Terminal-Getting-Started/#faq

- Then, copy and paste the following file into the ARDUPY drive that gets created inside your PC file explorer:
https://files.seeedstudio.com/wiki/Wio-Terminal/res/ArduPy_wio_terminal_lastest.uf2

- After that, open a serial console, connect to Wio Terminal, and type the following:
```sh
from machine import Map
```

- Finally, type "Map." and press "tab" on the keyboard to view the function names:

![1612257049(1)](https://user-images.githubusercontent.com/20147381/106577673-a7b93580-6564-11eb-824b-a25811360953.png)

You can see that WIO_LIGHT corresponds to the light sensor, whereas WIO_IR corresponds to the IR Emitter.

And you can check here how the Map function can be used combined with Pin function:
https://wiki.seeedstudio.com/ArduPy/#map

Please follow this video playlist to learn more about the ArduPy functions and other demos:
https://youtube.com/playlist?list=PLpH_4mf13-A2Ce5qaiMHwR8bwKhePvIee

Also, you could refer to our wiki pages:
https://wiki.seeedstudio.com/ArduPy/

For Micro-SD, please use the following library:
https://github.com/Seeed-Studio/seeed-ardupy-sdcard

For accelerometer, please use the following library:
https://github.com/Seeed-Studio/seeed-ardupy-lis3dhtr

Unfortunately, there is no USB OTG functionality on ArduPy yet.

Please understand that ArduPy is still very new and we are trying to bring more functions in the future. 

Best Regards,
Lakshantha

**Comment by ruppde** [comment]
ok, thanks a lot for the detailed answer
